name: Firebase Deploy after push

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_EDUCATION_PLATFORM }}'
          projectId: my-education-platform
          args: deploy --only hosting
